// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalTask.Data;

namespace TechnicalTask.Migrations
{
    [DbContext(typeof(DbDataContext))]
    partial class DbDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("TechnicalTask.Models.Department", b =>
                {
                    b.Property<int>("DbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DbCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("DbName")
                        .HasColumnType("TEXT");

                    b.HasKey("DbID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("TechnicalTask.Models.Employees", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentDbID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentDbID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TechnicalTask.Models.Employees", b =>
                {
                    b.HasOne("TechnicalTask.Models.Department", null)
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentDbID");
                });
#pragma warning restore 612, 618
        }
    }
}
